name: Run Unit Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
    paths:
      - "call-center-client/**" # run the job for UI app only

jobs:
  test-client:
    name: Test UI App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: call-center-client

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
